name: Build and Upload Node.js Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:23-alpine

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apk add --no-cache zip
        yarn

    - name: Build for production
      run: yarn build

    - name: Run unit tests
      run: yarn unit

    - name: Zip dist folder
      run: |
        echo "Creating zip from dist directory"
        zip -r dist.zip dist/
      
    - name: Upload zip artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist-artifact
        path: dist.zip
