name: Node.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Add these permissions
permissions:
  contents: write  # This allows creating releases

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ "23" ]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: yarn
    - run: yarn build
    - name: Zip dist folder
      run: |
        echo "Creating zip from dist directory"
        zip -r dist.zip dist/
      
    # Upload to release
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: dist.zip
        tag_name: stable
        name: Stable Build
        body: Latest stable build
        draft: false
        prerelease: false
